import os


class Compiler:
    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        self.namespace = "minecraft"
        os.makedirs(self.output_dir, exist_ok=True)
    
    def set_namespace(self, namespace: str):
        self.namespace = namespace
    
    def compile(self, function_name: str):
        self.current_function = function_name
        function_path = os.path.join(self.output_dir, f"{function_name}.mcfunction")
        
        compiled_lines = []
        
        with open(function_path, 'w') as f:
            f.write(f"# Generated by MCFunPy: {function_name}\n")
            f.write(f"# Namespace: {self.namespace}\n\n")
            for line in compiled_lines:
                f.write(line + "\n")
        
        return f"Successfully compiled {function_name}.mcfunction"